### ISSUE TITLE
methods may need to pass through an appropriate `strict` argument to `modify_defaults()`

### ISSUE THREAD

**Issue by TimTaylor** [epiverse-trace/linelist#63]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [x] I have the most recent version of the package and R
 - [x] I have found a bug
 - [x] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

``` r
library(linelist)
dat <- data.frame(a=1)
ll <- make_linelist(dat, a = "a", allow_extra = TRUE)
ll["a"]
#> Error in modify_defaults(tags_defaults(), new_tags): Unknown variable types: a
#>   Use only tags listed in `tags_names()`, or set `allow_extra = TRUE`
```

<sup>Created on 2023-04-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

~I think the issue is that methods need to pass through an appropriate `strict` argument depending on whether or not extra tags have been allowed~

---------

**Comment by Bisaloo** [comment]
Thanks a lot for the report and apologies for the delay! This issue got lost in a sea of notifications.
