### ISSUE TITLE
Compatibility linelist-dplyr

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/linelist#67]
Hi Hugo, I was using `linelist` to build one of the pipelines for the case studies I'm working on, and I realised that there were some unexpected results, particularly when using the `mutate()` and `filter()` functions from `dplyr`.
I was creating a reproducible example for this when @jamesmbaazam  brought to my attention (thanks James for all your help) that there is a wip [vignette that talks about this](https://github.com/epiverse-trace/linelist/pull/53/commits/b5990bb0f1d2efbbd6dc95b0abbeff6233a485ad)- I think it'd be very useful to bring this information to the forefront for users, so that they don't assume that this is a bug. Also, if this is possible, I think that `linelist` objects should be made compatible with all `dplyr` functions, as they are most widely used and taught to public health practitioners.
Let me know what you think, many thanks!

**Comment by Bisaloo** [comment]
Hi Carmen, thanks for the report! I agree compatibility with dplyr should be a priority for linelist. 

I can finish the vignette to improve the documentation on this topic. Note however that this will only work for linelist development version for now. You can install the development version with:

```r
pak::pak("epiverse-trace/linelist")
```

Please give the development version a try and let me know if you are still encountered unexpected behaviour with dplyr :pray:

**Comment by CarmenTamayo** [comment]
Thanks @Bisaloo for your help!

**Comment by Bisaloo** [comment]
For context in case anyone stumbles upon this issue. The `mutate()` issue has been fixed in https://github.com/epiverse-trace/linelist/pull/54. 

If you still encounter issues after update linelist (`pak::pak("epiverse-trace/linelist")`), please restart your R session and open a new issue with a [reproducible example](https://reprex.tidyverse.org/) if the error still persists then.
