### ISSUE TITLE
Tagging and validating aggregated epi data

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/linelist#78]
Last month we had a meeting with the HARMONIZE team, where we discussed best ways to link climate and epi data, and identified opportunities for collaboration with Epiverse. 
One of the issues that we identified was the lack of wrangling and cleaning tools for aggregated data, which is the most common format for climate data, often the format found for outbreak data (e.g., in situation reports), and therefore the format that would have to be used to merge both types of dataset. 
When discussing the overlap between both projects, we realised that there is an existing gap that could be addressed using `linelist` functionality, namely the tagging and validation feature. HARMONIZE collaborators mentioned that it would be very valuable to extend this feature to tag aggregated data, to prevent the accidental loss of data in spatiotemporal units (e.g., data from a certain location overtime) in the subsequent steps of the analysis.

At the moment `linelist` only provides functions to handle individual level data, I'm raising this issue here to have a discussion about expanding the functionality of the package to also provide functions for aggregated data

**Comment by Bisaloo** [comment]
I'm interested in expanding linelist's functionality. Could we have a chat at some point (whether when we meet in person in two weeks or via zoom earlier) so you can walk me through what was discussed at the workshop on this topic?

**Comment by CarmenTamayo** [comment]
Yes of course, I'm at IDDconf this week, but let me know your availability for next week

**Comment by Bisaloo** [comment]
Closing this in favour of https://github.com/orgs/epiverse-trace/discussions/221 and https://github.com/epiverse-trace/datatagr. Let's continue the discussion there.
